
debug = 0
verbose = 0
generate = 1
#bind = 127.0.0.1:9555
#btcnode = 127.0.0.1:8333
peer = node.qbitcoin.net
# hidden-peer: connect to it like a pinned peer, but never advertise it to other peers
# (use for private peers reachable from this node but not from the public network)
#hidden_peer = 10.0.0.2:9555
dbi = sqlite
database = /var/lib/qbitcoin/qbitcoin.sqlite
log = syslog
loglevel = info

