
debug = 0
verbose = 0
generate = 1
#bind = 127.0.0.1
#btcnode = 127.0.0.1:8333
peer = node.qbitcoin.net
# hidden-peer: never advertise this peer to others (and hide it as block/tx origin).
# This alone does NOT make us connect to it; to also connect, list the same address under "peer".
#hidden_peer = 10.0.0.2
dbi = sqlite
database = /var/lib/qbitcoin/qbitcoin.sqlite
log = syslog
loglevel = info

